name: Test Repo
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup debug session
        uses: csexton/debugger-action@master: 5
